import type { Metadata } from "next";
import { Barlow } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./components/ThemeProvider";

const barlow = Barlow({
  weight: ["400", "500", "600"],
  style: "normal",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Boring Icons",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={barlow.className} suppressHydrationWarning>
      <body className="antialiased bg-surface text-fg">
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
